### ISSUE TITLE
Algorithm?

### ISSUE THREAD

**Issue by srush** [kernelmachine/balanced-kmeans#1]
Hey Suchin, 

This project looks really neat. What algorithm are you using for balancing? Seems like there are a bunch of different options here, and I can't tell which is good.

**Comment by kernelmachine** [comment]
Hey Sasha, we are using the algorithm described at the beginning of section 2 here: https://arxiv.org/abs/2303.14177

We are using the auction algorithm to solve the balanced linear assignment problem. We have a couple good references in that section, in particular Mike's implementation from the BASE layers project which we applied here.

**Comment by srush** [comment]
thanks!

**Comment by srush** [comment]
(llama3.1 is awesome congrats)

**Comment by kernelmachine** [comment]
Haha, thanks Sasha!! we're so glad it's out in the world :)
